image: node:7.4.0

pipelines:
  default: # Pipelines that run automatically on a commit to a branch
    - step:
        script: # Modify the commands below to build your repository.
          - git config --global user.email "Frankie@potentialife.com"
          - git config --global user.name "Frankie"
          - ssh-add -l
          - ssh-add ~/.ssh/identity
          - git config remote.origin.url https://x-token-auth:$REPOSITORY_OAUTH_ACCESS_TOKEN@bitbucket.org/Tonio31/program_2_0.git
          - ssh -T hg@bitbucket.org
          - npm install
          - npm install -g gulp
          - gulp pushTag
          - npm run build
          - npm run setKarmaGlobals -- --browser PhantomJS
          - npm run test/phantomjs --silent
  branches:
    dev:
      - step:
          script:
            - npm install
            - npm run build
            - npm run deploy
    PROD:
      - step:
          script:
            - npm install
            - npm run build -- --phase PROD
            - npm run deploy -- --phase PROD

