image: node:7.4.0

pipelines:
  default: # Pipelines that run automatically on a commit to a branch
    - step:
        script: # Modify the commands below to build your repository.
          - npm install
          - npm install -g gulp
          - npm run build
          - npm run setKarmaGlobals -- --browser PhantomJS
          - npm run test/phantomjs --silent
  branches:
    dev:
      - step:
          script:
            - npm install
            - npm run build
            - npm run deploy
            - ./bugsnag-deploy.sh UAT
    PROD:
      - step:
          script:
            - npm install
            - git config --global user.email "Frankie@potentialife.com"
            - git config --global user.name "Frankie"
            - npm run bumpVersionNumber
            - npm run build -- --phase PROD
            - npm run deploy -- --phase PROD
            - npm run addGitTagToRepo
            - npm run notifyTicketsChanel -- --phase PROD
            - ./bugsnag-deploy.sh PROD

