image: node:7.4.0

pipelines:
  default: # Pipelines that run automatically on a commit to a branch
    - step:
        caches:
          - node
        script:
          - npm install
          - npm install -g gulp
          - npm run build
          - npm run setKarmaGlobals -- --browser PhantomJS
          - npm run test/phantomjs --silent
  branches:
    feature/newstyle:
      - step:
          name: Build and deploy on UAT
          deployment: test
          script:
            - npm install
            - npm run build -- --phase UAT
            - npm run deploy -- --phase UAT
            - npm run deploy -- --phase UAT --index
            - ./bugsnag-deploy.sh UAT
    dev:
      - step:
          name: Build and deploy on UAT
          deployment: test
          script:
            - npm install
            - git config --global user.email "Frankie@potentialife.com"
            - git config --global user.name "Frankie"
            - npm run increaseVersionNumber
            - npm run build -- --phase UAT
            - npm run deploy -- --phase UAT
            - npm run deploy -- --phase UAT --index
            - ./bugsnag-deploy.sh UAT
    PROD:
      - step:
          name: Build and deploy on PROD
          deployment: production
          script:
            - npm install
            - git config --global user.email "Frankie@potentialife.com"
            - git config --global user.name "Frankie"
            - npm run build -- --phase PROD
            - npm run deploy -- --phase PROD
            - npm run deploy -- --phase PROD --index
            - npm run addGitTagToRepo
            - npm run notifyTicketsChanel -- --phase PROD
            - ./bugsnag-deploy.sh PROD
